"""empty message

Revision ID: 0b86cd2ed10e
Revises: c5cb145e17ef
Create Date: 2020-11-29 16:15:53.024954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b86cd2ed10e'
down_revision = 'c5cb145e17ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_partner', sa.Column('join_cnt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    # Fix data type of rating column
    op.alter_column(table_name='favorite_partner',column_name='rating',type_=sa.Numeric(10,2))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite_partner', 'join_cnt')
    # ### end Alembic commands ###
