"""empty message

Revision ID: 0b8adb47d3fd
Revises: d624b426ec2a
Create Date: 2020-11-23 12:58:58.324565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8adb47d3fd'
down_revision = 'd624b426ec2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_partner',
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('partner_name', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_partner')
    # ### end Alembic commands ###
