"""empty message

Revision ID: 29ec398037ab
Revises: 
Create Date: 2019-06-02 11:20:44.377592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ec398037ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('singer',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('performed_by', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('pic_url', sa.String(length=200), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('is_vip', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('performance',
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('artist', sa.String(length=100), nullable=True),
    sa.Column('ensemble_type', sa.String(length=10), nullable=True),
    sa.Column('child_count', sa.Integer(), nullable=True),
    sa.Column('app_uid', sa.String(length=20), nullable=True),
    sa.Column('arr_key', sa.String(length=30), nullable=True),
    sa.Column('orig_track_city', sa.String(length=40), nullable=True),
    sa.Column('orig_track_country', sa.String(length=40), nullable=True),
    sa.Column('media_url', sa.String(length=200), nullable=True),
    sa.Column('video_media_url', sa.String(length=200), nullable=True),
    sa.Column('video_media_mp4_url', sa.String(length=200), nullable=True),
    sa.Column('web_url', sa.String(length=200), nullable=True),
    sa.Column('cover_url', sa.String(length=100), nullable=True),
    sa.Column('total_performers', sa.Integer(), nullable=True),
    sa.Column('total_listens', sa.Integer(), nullable=True),
    sa.Column('total_loves', sa.Integer(), nullable=True),
    sa.Column('total_comments', sa.Integer(), nullable=True),
    sa.Column('total_commenters', sa.Integer(), nullable=True),
    sa.Column('performed_by', sa.String(length=50), nullable=True),
    sa.Column('performed_by_url', sa.String(length=50), nullable=True),
    sa.Column('owner_account_id', sa.Integer(), nullable=False),
    sa.Column('owner_lat', sa.Float(), nullable=True),
    sa.Column('owner_lon', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_account_id'], ['singer.account_id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('performance_singer',
    sa.Column('performance_key', sa.String(length=30), nullable=False),
    sa.Column('singer_account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['performance_key'], ['performance.key'], ),
    sa.ForeignKeyConstraint(['singer_account_id'], ['singer.account_id'], ),
    sa.PrimaryKeyConstraint('performance_key', 'singer_account_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_singer')
    op.drop_table('performance')
    op.drop_table('singer')
    # ### end Alembic commands ###
