"""empty message

Revision ID: 38bd6b6bd67c
Revises: 5a88314ea9ec
Create Date: 2021-05-11 13:03:18.500257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38bd6b6bd67c'
down_revision = '5a88314ea9ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('singer_following',
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('handle', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('pic_url', sa.String(length=200), nullable=True),
    sa.Column('is_following', sa.Boolean(), nullable=True),
    sa.Column('is_vip', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('singer_following')
    # ### end Alembic commands ###
