"""empty message

Revision ID: 4dc27bafe7b5
Revises: 562783c5ea8f
Create Date: 2020-04-05 11:18:37.445856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc27bafe7b5'
down_revision = '562783c5ea8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_favorite',
    sa.Column('favorited_by_username', sa.String(length=50), nullable=False),
    sa.Column('performance_key', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['performance_key'], ['performance.key'], ),
    sa.PrimaryKeyConstraint('favorited_by_username', 'performance_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_favorite')
    # ### end Alembic commands ###
