"""empty message

Revision ID: 5a88314ea9ec
Revises: 0b86cd2ed10e
Create Date: 2020-12-08 16:34:25.849881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a88314ea9ec'
down_revision = '0b86cd2ed10e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smule_list',
    sa.Column('list_type', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('list_type', 'item_name')
    sql="""
insert into smule_list(list_type,item_name) values('EXCLUDE_INVITE_ANALYTICS','3 Old Melodies');
insert into smule_list(list_type,item_name) values('EXCLUDE_INVITE_ANALYTICS','Ar Rahman Medley');
insert into smule_list(list_type,item_name) values('EXCLUDE_INVITE_ANALYTICS','Kaun Tujhe Bahut Pyaar Karte Hai');
insert into smule_list(list_type,item_name) values('EXCLUDE_INVITE_ANALYTICS','Open Mic');
insert into smule_list(list_type,item_name) values('EXCLUDE_INVITE_ANALYTICS','Medley Old Songs');
insert into smule_list(list_type,item_name) values('EXCLUDE_INVITE_ANALYTICS','Medley');
insert into smule_list(list_type,item_name) values('EXCLUDE_INVITE_ANALYTICS','Mashup');
insert into smule_list(list_type,item_name) values('EXCLUDE_INVITE_ANALYTICS','Old Bollywood Mashup');
insert into smule_list(list_type,item_name) values('EXCLUDE_PARTNER','Nav_fighter');
insert into smule_list(list_type,item_name) values('INCLUDE_PARTNER','Daph_Stan');
insert into smule_list(list_type,item_name) values('INCLUDE_PARTNER','gsatya27');
insert into smule_list(list_type,item_name) values('INCLUDE_PARTNER','inderjitmanga');
insert into smule_list(list_type,item_name) values('INCLUDE_PARTNER','mala_tandirala');
insert into smule_list(list_type,item_name) values('INCLUDE_PARTNER','MruduJ');
insert into smule_list(list_type,item_name) values('INCLUDE_PARTNER','sai_sistla');
insert into smule_list(list_type,item_name) values('INCLUDE_PARTNER','seethamraju');
insert into smule_list(list_type,item_name) values('INCLUDE_PARTNER','siddlots');
insert into smule_list(list_type,item_name) values('INCLUDE_PARTNER','skongattil');
insert into smule_list(list_type,item_name) values('INCLUDE_PARTNER','SmitaL7');
insert into smule_list(list_type,item_name) values('INCLUDE_PARTNER','svyas07');
insert into smule_list(list_type,item_name) values('INCLUDE_PARTNER','yaak_sumney');
"""
    op.execute(sql)
    )
    op.drop_table('favorite_partner')
    op.drop_table('song_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song_list',
    sa.Column('list_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('fixed_title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('list_type', 'fixed_title', name='song_list_pkey')
    )
    op.create_table('favorite_partner',
    sa.Column('account_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('partner_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('rating', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('favorite_cnt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('manual_override_ind', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('performance_cnt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('join_cnt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('account_id', name='favorite_partner_pkey')
    )
    op.drop_table('smule_list')
    # ### end Alembic commands ###
