"""empty message

Revision ID: 6760eedb73e1
Revises: 654948a05e7c
Create Date: 2023-12-17 18:53:42.424936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6760eedb73e1'
down_revision = '654948a05e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sing_following_backup')
    with op.batch_alter_table('performance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_pic_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance', schema=None) as batch_op:
        batch_op.drop_column('display_pic_url')

    op.create_table('sing_following_backup',
    sa.Column('account_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('handle', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('pic_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('is_following', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_vip', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('verified_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
