"""empty message

Revision ID: a432f4f9f9fb
Revises: 326d72b473f8
Create Date: 2022-10-08 16:43:26.625078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a432f4f9f9fb'
down_revision = '326d72b473f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('i_perfsinger_singer', 'performance_singer', ['singer_account_id'], unique=False)
    op.create_index('i_perffav_perfkey', 'performance_favorite', ['performance_key'], unique=False)
    op.add_column('performance', sa.Column('parent_key', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performance', 'parent_key')
    op.drop_index('i_perffav_perfkey', table_name='performance_favorite')
    op.drop_index('i_perfsinger_singer', table_name='performance_singer')
    # ### end Alembic commands ###
