"""empty message

Revision ID: a6916bbb6160
Revises: 29ec398037ab
Create Date: 2019-06-03 22:07:35.885916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6916bbb6160'
down_revision = '29ec398037ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance', sa.Column('filename', sa.String(length=200), nullable=True))
    op.add_column('performance', sa.Column('owner_handle', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performance', 'owner_handle')
    op.drop_column('performance', 'filename')
    # ### end Alembic commands ###
