"""empty message

Revision ID: c5cb145e17ef
Revises: 0b8adb47d3fd
Create Date: 2020-11-24 17:34:26.990947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5cb145e17ef'
down_revision = '0b8adb47d3fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_partner', sa.Column('favorite_cnt', sa.Integer(), nullable=True))
    op.add_column('favorite_partner', sa.Column('manual_override_ind', sa.Boolean(), nullable=True))
    op.add_column('favorite_partner', sa.Column('performance_cnt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite_partner', 'performance_cnt')
    op.drop_column('favorite_partner', 'manual_override_ind')
    op.drop_column('favorite_partner', 'favorite_cnt')
    # ### end Alembic commands ###
