"""empty message

Revision ID: d624b426ec2a
Revises: ae856013567a
Create Date: 2020-11-15 16:29:41.470518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd624b426ec2a'
down_revision = 'ae856013567a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance', sa.Column('performer_handles', sa.String(length=200), nullable=True))
    op.add_column('performance', sa.Column('performer_ids', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performance', 'performer_ids')
    op.drop_column('performance', 'performer_handles')
    # ### end Alembic commands ###
