"""empty message

Revision ID: f0be44d66ecb
Revises: 23d0341b90e5_manual
Create Date: 2020-06-06 15:21:29.551372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0be44d66ecb'
down_revision = '23d0341b90e5_manual'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance', sa.Column('expire_at', sa.DateTime(), nullable=True))
    op.add_column('performance', sa.Column('fixed_title', sa.String(length=100), nullable=True))
    op.add_column('performance', sa.Column('perf_status', sa.String(length=1), nullable=True))
    op.add_column('performance', sa.Column('performers', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performance', 'performers')
    op.drop_column('performance', 'perf_status')
    op.drop_column('performance', 'fixed_title')
    op.drop_column('performance', 'expire_at')
    # ### end Alembic commands ###
