"""empty message

Revision ID: f6924a956897
Revises: 7006dbd22793
Create Date: 2019-06-06 04:20:01.990609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6924a956897'
down_revision = '7006dbd22793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performance', 'cover_url')
    op.drop_column('performance', 'artist')
    op.drop_column('performance', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('performance', sa.Column('artist', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('performance', sa.Column('cover_url', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
