CREATE OR REPLACE VIEW all_performances AS
SELECT  p.key,
        p.type,
        p.ensemble_type,
        p.child_count,
        p.app_uid,
        p.arr_key,
        p.orig_track_city,
        p.orig_track_country,
        p.media_url,
        p.video_media_url,
        p.video_media_mp4_url,
        p.web_url,
        p.total_performers,
        p.total_listens,
        p.total_loves,
        p.total_comments,
        p.total_commenters,
        p.performed_by,
        p.performed_by_url,
        p.owner_account_id,
        p.owner_lat,
        p.owner_lon,
        p.created_at,
        p.updated_at,
        p.filename,
        p.owner_handle,
        p.owner_pic_url,
        p.artist,
        p.cover_url,
        p.title,
        p.fixed_title,
        split_part(p.key::text, '_'::text, 1) AS instance_key,
        COALESCE(s.performed_by, p.owner_handle) AS partner_name,
        COALESCE(s.pic_url, p.owner_pic_url) AS partner_pic_url,
        p.performers
FROM    performance p
        left outer join singer s on s.performed_by = p.performers
;
